### PR TITLE
Table name

### PR DESCRIPTION
**Pull request by russmack**
Hi Daniel, here's something else I needed - setting a table name which I could use in output after processing.

---
This change is [Reviewable](https://reviewable.io/reviews/frictionlessdata/tableschema-go/76)

### CODE REVIEW

**Comment by danielfireman** [comment]
Hi @russmack ! Would you mind sending a little bit more context on your use case?

Asking because of this change adds a field to the `Schema` which is not part of the [Table Schema](https://frictionlessdata.io/specs/table-schema/) specification. Thus it is worth to put a little bit more thought on that.

Furthermore, would you mind sending these two last commits (adding tests) as a separate PR? It would be super nice! :smile: 

cc/ @roll

**Comment by russmack** [comment]
Ah right.  I used it to build SQL create table statements - _func (s *Schema) ToPostgreSQL() string {_ ...

Separate PR for those last two commits coming up...

**Comment by danielfireman** [comment]
What you described sounds a lot like Storage/Plugins tfrom [tableschema-py](https://github.com/frictionlessdata/tableschema-py). 

I won't be able to work on that right now, but I would be super happy to help/guide/discuss (maybe via VC meeting). If that sounds good to you, I believe the best way to start is opening an issue and describing your use case. How does that sound?

**Comment by russmack** [comment]
I'll have to add that to my todo list for now.  I've had a very brief look and will need more time for it.

**Pull request closed without merging**
