### PR TITLE
Added matryer/is to the tests

### PR DESCRIPTION
**Pull request by ThatEric**

### CODE REVIEW

**Comment by ThatEric** [comment]
Sure I'll look at this today. Interesting that Travis CI didn't like this.

**Comment by danielfireman** [comment]
[The job](https://travis-ci.org/frictionlessdata/tableschema-go/jobs/286860163) is confused, somehow. It says there is a reference to reflect at line 563, but the reference does not seem to exist in the [new version of the file](https://github.com/ThatEric/tableschema-go/blob/ac903445909d1518164f6b9ced37b9c68e8dabdb/schema/schema_test.go).

Maybe you a new push (re-organize imports in schema_test.go leaving non-stdlib imports at the end  would be great) to the branch would trigger a new correct job?

**Comment by ThatEric** [comment]
Yeah I noticed that too, it's really odd. I redid the imports and it still doesn't like it.

**Comment by danielfireman** [comment]
Thanks, @ThatEric ! Great stuff!

**Comment by danielfireman** [comment]
Just pushed 7972782596e63cf408b6d2233a1e726b65a671a4 , which takes care of some few left overs. Now everything is compiling properly.

Tests are looking awesome!

**Pull request merged**
